$schema: "https://json-schema.org/draft/2020-12/schema"
description: main configuration schema for the workflow
properties:
  sample_sheet:
    type: string
    description: path to sample sheet TSV file
  gene_expression:
    type: string
    description: path to ref_data folder

required:
  - sample_sheet
