$schema: "https://json-schema.org/draft/2020-12/schema"
description: main configuration schema for the workflow
properties:
  sample_sheet:
    type: string
    description: path to sample sheet TSV file
  multi_config_csv_sections:
    type: object
    description: configuration options for the multi config csv file

required:
  - sample_sheet
  - multi_config_csv_sections
