# Link the raw fastq files into an input directory and
# make sure they are named EXACTLY how Cell Ranger needs
# them. Sigh.
# -----------------------------------------------------
rule follow_pedantic_cell_ranger_naming_scheme:
    input:
        fq1=lambda wc: get_input_file(wc, "read1"),
        fq2=lambda wc: get_input_file(wc, "read2"),
    output:
        fq1="<results>/input/{pool_id}_{feature_type}/{pool_id}_S1_L00{lane_number}_R1_001.fastq.gz",
        fq2="<results>/input/{pool_id}_{feature_type}/{pool_id}_S1_L00{lane_number}_R2_001.fastq.gz",
    log:
        "<logs>/input/{pool_id}_{feature_type}/{pool_id}_{feature_type}_S1_L00{lane_number}_001.log",
    localrule: True
    conda:
        "../envs/bash_coreutils.yaml"
    params:
        fq1=lambda wc, input, output: path.relpath(
            str(input.fq1), start=path.dirname(output.fq1)
        ),
        fq2=lambda wc, input, output: path.relpath(
            str(input.fq2), start=path.dirname(output.fq2)
        ),
    shell:
        "( ln --symbolic {params.fq1} {output.fq1}; "
        "  ln --symbolic {params.fq2} {output.fq2}; "
        ") >{log} 2>&1 "


# Create a multi config CSV file for Cell Ranger.
# -----------------------------------------------------
rule create_cellranger_multi_config_csv:
    input:
        pool_sheet=lookup(within=config, dpath="pool_sheet"),
        fq1=lambda wc: get_sample_fastqs(wc, "R1"),
        fq2=lambda wc: get_sample_fastqs(wc, "R2"),
        feature_reference=lookup(
            within=config,
            dpath="multi_config_csv_sections/feature/reference",
            default=[],
        ),
        multiplexing=branch(
            lookup(
                within=config,
                dpath="multi_config_csv_sections/multiplexing/activate",
            ),
            then=lookup(
                within=config,
                dpath="multi_config_csv_sections/multiplexing/tsv",
                default=[],
            ),
            otherwise=[],
        ),
    output:
        multi_config_csv="<results>/input/{pool_id}.cell_ranger_multi_config.csv",
    log:
        "<logs>/input/{pool_id}.cell_ranger_multi_config.log",
    localrule: True
    conda:
        "../envs/tidyverse.yaml"
    params:
        multi_config_csv_sections=lookup(
            within=config, dpath="multi_config_csv_sections"
        ),
    script:
        "../scripts/create_cellranger_multi_config_csv.R"


# Run cellranger multi on one sample.
# -----------------------------------------------------
rule cellranger_multi_run:
    input:
        multi_config_csv="<results>/input/{pool_id}.cell_ranger_multi_config.csv",
        fq1=lambda wc: get_sample_fastqs(wc, "R1"),
        fq2=lambda wc: get_sample_fastqs(wc, "R2"),
        reference=lookup(
            within=config,
            dpath="multi_config_csv_sections/gene-expression/reference",
            default=[],
        ),
    output:
        csv="<results>/cellranger/{pool_id}/outs/config.csv",
    log:
        "<logs>/cellranger_multi/multi_run_{pool_id}.log",
    conda:
        "../envs/cellranger.yaml"
    threads: 16
    resources:
        mem_mb=lambda wc, threads: threads * 4000,
    params:
        out_dir=lambda wc, output: output["csv"].replace("outs/config.csv", ""),
        mem_gb=lambda wc, resources: math.floor(resources.mem_mb / 1000) + 5,
        cellranger_version=str(CELLRANGER_VERSION),  # track version changes to retrigger cellranger_multi_run upon newly installed cellranger version
    shell:
        "(rm -rf {params.out_dir}; "
        " cellranger multi "
        "  --id={wildcards.pool_id} "
        "  --output-dir={params.out_dir} "
        "  --csv={input.multi_config_csv} "
        "  --localcores={threads} "
        "  --localmem={params.mem_gb}; "
        ") >{log} 2>&1 "


# Check all of the cellranger output files required by the setup


rule cellranger_multi_files_summaries:
    input:
        csv_copy="<results>/cellranger/{pool_id}/outs/config.csv",
    output:
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/metrics_summary.csv"
        ),
        report(
            update(
                "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/web_summary.html"
            ),
            caption="../report/cellranger_multi_web.rst",
            category="cellranger",
            subcategory="per-sample reports",
            labels={"sample": "{sample_id}"},
        ),
    log:
        "<logs>/cellranger_multi/summary_files/summaries_{pool_id}_{sample_id}.log",
    localrule: True
    conda:
        "../envs/bash_coreutils.yaml"
    threads: 1
    script:
        "../scripts/check_cellranger_outputs.sh"


# QC output that is only generated by cellranger versions 10 and above
rule cellranger_multi_wc_cellranger_10:
    input:
        csv_copy="<results>/cellranger/{pool_id}/outs/config.csv",
    output:
        update("<results>/cellranger/{pool_id}/outs/qc_library_metrics.csv"),
        update(
            "<results>/cellranger/{pool_id}/outs/qc_sample_metrics.csv",
        ),
        report(
            update(
                "<results>/cellranger/{pool_id}/outs/qc_report.html",
            ),
            caption="../report/cellranger_multi_qc.rst",
            category="cellranger",
            subcategory="pool reports",
            labels={"pool": "{pool_id}"},
        ),
    log:
        "<logs>/cellranger_multi/summary_files/qc_{pool_id}.log",
    localrule: True
    conda:
        "../envs/bash_coreutils.yaml"
    threads: 1
    script:
        "../scripts/check_cellranger_outputs.sh"


# `feature_reference.csv` is produced by a bunch of modes, at least:
# * multiplexing (config["multiplexing"]["activate"] == True)
# * Antigen Capture (Feature Type)
# * Antibody Capture (Feature Type)
# * CRISPR Guide Capture (Feature Type)
# We track it in a separate rule, to allow for it to be tracked for all these
# analysis types, without causing ambiguity between rules.
rule cellranger_multi_feature_reference:
    input:
        csv_copy="<results>/cellranger/{pool_id}/outs/config.csv",
    output:
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>feature_reference.csv"
        ),
    log:
        "<logs>/cellranger_multi/feature_reference_{pool_id}.log",
    localrule: True
    conda:
        "../envs/bash_coreutils.yaml"
    threads: 1
    script:
        "../scripts/check_cellranger_outputs.sh"


# multiplexing outputs, according to:
# https://www.10xgenomics.com/support/software/cell-ranger/latest/analysis/outputs/cr-3p-outputs-cellplex


rule cellranger_multi_files_multiplexing_global:
    input:
        csv_copy="<results>/cellranger/{pool_id}/outs/config.csv",
    output:
        update(
            "<results>/cellranger/{pool_id}/outs/<multi>multiplexing_analysis/assignment_confidence_table.csv"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi>multiplexing_analysis/cells_per_tag.json"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi>multiplexing_analysis/tag_calls_per_cell.csv"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi>multiplexing_analysis/tag_calls_summary.csv"
        ),
    log:
        "<logs>/cellranger_multi/multiplexing_files/multiplexing_global_{pool_id}.log",
    localrule: True
    conda:
        "../envs/bash_coreutils.yaml"
    threads: 1
    script:
        "../scripts/check_cellranger_outputs.sh"


rule cellranger_multi_files_antibody_antigen_per_sample:
    input:
        csv_copy="<results>/cellranger/{pool_id}/outs/config.csv",
    output:
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/<count>aggregate_barcodes.csv"
        ),
    log:
        "<logs>/cellranger_multi/antibody_antigen_per_sample_{pool_id}_{sample_id}.log",
    localrule: True
    conda:
        "../envs/bash_coreutils.yaml"
    threads: 1
    script:
        "../scripts/check_cellranger_outputs.sh"


rule cellranger_multi_files_antigen_specificity_per_sample:
    input:
        csv_copy="<results>/cellranger/{pool_id}/outs/config.csv",
    output:
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/antigen_analysis/antigen_specificity_scores.csv",
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/antigen_analysis/per_barcode.csv",
        ),
    log:
        "<logs>/cellranger_multi/antigen_specificity_per_sample_{pool_id}_{sample_id}.log",
    localrule: True
    conda:
        "../envs/bash_coreutils.yaml"
    threads: 1
    script:
        "../scripts/check_cellranger_outputs.sh"


rule cellranger_multi_files_multiplexing_crispr_global:
    input:
        csv_copy="<results>/cellranger/{pool_id}/outs/config.csv",
    output:
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>crispr_analysis/cells_per_protospacer.json"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>crispr_analysis/feature_reference.csv"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>crispr_analysis/perturbation_effects_by_feature"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>crispr_analysis/perturbation_effects_by_target"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>crispr_analysis/perturbation_efficiencies_by_feature.csv"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>crispr_analysis/perturbation_efficiencies_by_target.csv"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>crispr_analysis/protospacer_calls_per_cell.csv"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>crispr_analysis/protospacer_calls_summary.csv"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>crispr_analysis/protospacer_umi_thresholds.csv"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>crispr_analysis/protospacer_umi_thresholds.json"
        ),
    log:
        "<logs>/cellranger_multi/multiplexing_files/multiplexing_crispr_global_{pool_id}.log",
    localrule: True
    conda:
        "../envs/bash_coreutils.yaml"
    threads: 1
    script:
        "../scripts/check_cellranger_outputs.sh"


# "Gene Expression" output files
rule cellranger_multi_files_gene_expression_global:
    input:
        csv_copy="<results>/cellranger/{pool_id}/outs/config.csv",
    output:
        update("<results>/cellranger/{pool_id}/outs/<multi><count>raw_molecule_info.h5"),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>raw_feature_bc_matrix/barcodes.tsv.gz"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>raw_feature_bc_matrix/features.tsv.gz"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>raw_feature_bc_matrix/matrix.mtx.gz"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>raw_feature_bc_matrix.h5"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>unassigned_alignments.bam"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi><count>unassigned_alignments.bam.bai"
        ),
    log:
        "<logs>/cellranger_multi/gene_expression_files/gex_global_{pool_id}.log",
    localrule: True
    conda:
        "../envs/bash_coreutils.yaml"
    threads: 1
    script:
        "../scripts/check_cellranger_outputs.sh"


# gene_expression output that is only generated by cellranger versions 10 and above
rule cellranger_multi_files_gene_expression_global_sample_collections:
    input:
        csv_copy="<results>/cellranger/{pool_id}/outs/config.csv",
    output:
        update("<results>/cellranger/{pool_id}/outs/filtered_feature_bc_matrix.h5"),
        update(
            "<results>/cellranger/{pool_id}/outs/filtered_feature_bc_matrix/barcodes.tsv.gz"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/filtered_feature_bc_matrix/features.tsv.gz"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/filtered_feature_bc_matrix/matrix.mtx.gz"
        ),
    log:
        "<logs>/cellranger_multi/gene_expression_files/gex_global_{pool_id}_sample_collections.log",
    localrule: True
    conda:
        "../envs/bash_coreutils.yaml"
    threads: 1
    script:
        "../scripts/check_cellranger_outputs.sh"


rule cellranger_multi_files_gene_expression_per_sample:
    input:
        csv_copy="<results>/cellranger/{pool_id}/outs/config.csv",
    output:
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/<count>sample_filtered_barcodes.csv"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/<count>sample_alignments.bam"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/<count>sample_alignments.bam.bai"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/<count>sample_filtered_feature_bc_matrix/barcodes.tsv.gz"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/<count>sample_filtered_feature_bc_matrix/features.tsv.gz"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/<count>sample_filtered_feature_bc_matrix/matrix.mtx.gz"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/<count>sample_filtered_feature_bc_matrix.h5"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/<count>sample_molecule_info.h5"
        ),
    log:
        "<logs>/cellranger_multi/gene_expression_files/gex_per_sample_{pool_id}_{sample_id}.log",
    localrule: True
    conda:
        "../envs/bash_coreutils.yaml"
    threads: 1
    script:
        "../scripts/check_cellranger_outputs.sh"


rule cellranger_multi_files_gene_expression_per_sample_cellranger_10:
    input:
        csv_copy="<results>/cellranger/{pool_id}/outs/config.csv",
    output:
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/sample_raw_feature_bc_matrix.h5",
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/sample_raw_feature_bc_matrix/barcodes.tsv.gz",
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/sample_raw_feature_bc_matrix/features.tsv.gz",
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/sample_raw_feature_bc_matrix/matrix.mtx.gz",
        ),
    log:
        "<logs>/cellranger_multi/gene_expression_files/gex_per_sample_{pool_id}_{sample_id}_cellranger_10.log",
    localrule: True
    conda:
        "../envs/bash_coreutils.yaml"
    threads: 1
    script:
        "../scripts/check_cellranger_outputs.sh"


# VDJ output files


rule cellranger_multi_files_vdj_reference:
    input:
        csv_copy="<results>/cellranger/{pool_id}/outs/config.csv",
    output:
        update("<results>/cellranger/{pool_id}/outs/vdj_reference/reference.json"),
        update("<results>/cellranger/{pool_id}/outs/vdj_reference/fasta/regions.fa"),
    log:
        "<logs>/cellranger_multi/vdj_reference_files_{pool_id}.log",
    localrule: True
    conda:
        "../envs/bash_coreutils.yaml"
    threads: 1
    script:
        "../scripts/check_cellranger_outputs.sh"


rule cellranger_multi_files_vdj_global:
    input:
        csv_copy="<results>/cellranger/{pool_id}/outs/config.csv",
    output:
        update(
            "<results>/cellranger/{pool_id}/outs/<multi>{vdj_type}/all_contig_annotations.bed"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi>{vdj_type}/all_contig_annotations.csv"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi>{vdj_type}/all_contig_annotations.json"
        ),
        update("<results>/cellranger/{pool_id}/outs/<multi>{vdj_type}/all_contig.bam"),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi>{vdj_type}/all_contig.bam.bai"
        ),
        update("<results>/cellranger/{pool_id}/outs/<multi>{vdj_type}/all_contig.fasta"),
        update(
            "<results>/cellranger/{pool_id}/outs/<multi>{vdj_type}/all_contig.fasta.fai"
        ),
        update("<results>/cellranger/{pool_id}/outs/<multi>{vdj_type}/all_contig.fastq"),
    log:
        "<logs>/cellranger_multi/{vdj_type}_files/{vdj_type}_global_{pool_id}.log",
    localrule: True
    conda:
        "../envs/bash_coreutils.yaml"
    threads: 1
    script:
        "../scripts/check_cellranger_outputs.sh"


rule cellranger_multi_files_vdj_per_sample:
    input:
        csv_copy="<results>/cellranger/{pool_id}/outs/config.csv",
    output:
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/airr_rearrangement.tsv"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/cell_barcodes.json"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/clonotypes.csv"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/concat_ref.bam"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/concat_ref.bam.bai"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/concat_ref.fasta"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/concat_ref.fasta.fai"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/consensus.bam"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/consensus.bam.bai"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/consensus.fasta"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/consensus.fasta.fai"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/consensus_annotations.csv"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/donor_regions.fa"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/filtered_contig_annotations.csv"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/filtered_contig.fasta"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/filtered_contig.fastq"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/vdj_contig_info.pb"
        ),
        update(
            "<results>/cellranger/{pool_id}/outs/per_sample_outs/{sample_id}/{vdj_type}/vloupe.vloupe"
        ),
    log:
        "<logs>/cellranger_multi/{vdj_type}_files/{vdj_type}_per_sample_{pool_id}_{sample_id}.log",
    localrule: True
    conda:
        "../envs/bash_coreutils.yaml"
    threads: 1
    script:
        "../scripts/check_cellranger_outputs.sh"
